server:
  port: 8080

moorse:
  integration: c98627b6-3940-4654-a2fd-f328508e8409
  api:
    url: https://api.moorse.io
  token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwYmwubWVuZGV6QGdtYWlsLmNvbSIsImlkQ2xpZW50IjoiZTc1N2E5ZjItYTEyZi00ODM2LWFjYmQtNTQzMzMyMzgwYmNjIiwiY3JlYXRlZCI6MTY0NjAwNDI5OTY3NSwicm9sZXMiOlsiUk9MRV9BUEkiLCJST0xFX0RBU0hCT0FSRCIsIlJPTEVfREFTSEJPQVJEX0dST1VQUyIsIlJPTEVfR1JPVVBTIiwiUk9MRV9JTlRFR1JBVElPTl9VU0VSIiwiUk9MRV9UUklBTCIsIlJPTEVfVVNFUlMiLCJST0xFX1dFQkhPT0siXSwiaWQiOjE2NiwiZXhwIjoxNjc3NTQwMjk5fQ.v9C_GzlVwgqUBi3uUanmU97s7638n3gYm2ATiFAzb2BDaOap_jq0AFVEZudXSPw3ytGRUL_NqTD4eOm2O5dazA

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: moorse-wa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  data:
    jpa:
      repositories:
        bootstrap-mode: default
